version: '3.8'

services:
  db:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3303:3306"
  web:
    build: .
    command: >
      sh -c "./wait-for-mysql.sh db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py test && 
      python manage.py runserver 0.0.0.0:8008"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    env_file:
      - .env


